### ISSUE TITLE
Run Trim Galore on all samples

### ISSUE THREAD

**Issue by sr320** [hputnam/Meth_Compare#12]

**Comment by sr320** [comment]
currently pending (job # 2044625). Script is here: https://gannet.fish.washington.edu/metacarcinus/mox_jobs/20200309_TrimGfroger.sh. Also added it to Meth_Compare_Pipeline.md.

**Comment by sr320** [comment]
@shellytrigg I do not think you need 500G of memory -
If you edit your job header your job should start running..

```
[sr320@mox2 sr320]$ squeue | grep srlab
           2026021     srlab nl_GR002 nclowell PD       0:00      1 (QOSGrpMemLimit)
           2044625     srlab TrimGfro   strigg PD       0:00      1 (QOSGrpMemLimit)
           2015335     srlab cmt_samt  ctarpey  R      21:49      1 n2193
```

**Comment by shellywanamaker** [comment]
Changed it to 100G. Job is running now #2054351

**Comment by sr320** [comment]
Completed

**Comment by shellywanamaker** [comment]
takes about 2 hours/ sample (80M reads) so should finish tomorrow night if all goes smoothly. I saw that the FASTQC is not being run because it is not in my path and I did not provide the path to FASTQC (I'm not sure how to do this since I didn't see an option to specify FASTQC path in TrimGalore or in FASTQC itself). So I will run fastqc on all TrimGalore trimmed data once it is finished.

**Comment by kubu4** [comment]
@shellytrigg - For future runs, you can add it to your `$PATH` like so:

```shell
printf "%s\n%s" "# Append bioinformatics stuff to PATH" 

"PATH=/gscratch/srlab/programs/fastqc_v0.11.8:$PATH" >> ~/.bash_profile
```
That will add two lines to your `.bash_profile` file. The file gets loaded any time you login, so FastQC will always be in your $PATH from then on.

```
# Append bioinformatics stuff to PATH
PATH=/gscratch/srlab/programs/fastqc_v0.11.8:$PATH" >> ~/.bash_profile
```
Alternatively/additionally, we/I can create a SLURM module for TrimGalore which would automatically add `cutadapt` and `fastqc` to the system $PATH. Then, anyone wanting to run TrimGalore would be able to load the SLURM module and `cutadapt` and `fastqc` will be ready to run without the need to modify any files and/or worry about remembering to specify program locations.

Also, when you do finally run FastQC, you can specify a thread count. I'd definitely recommend it.

**Comment by shellywanamaker** [comment]
@kubu4 awesome, thanks for the path solution! 

How many threads do you recommend for running FastQC on Mox?

**Comment by kubu4** [comment]
I'd use all 28. I think the FastQC documentation that FastQC will use 250MB of memory per thread, so maxing out the number of threads on Mox will be fine.

**Comment by shellywanamaker** [comment]
my trim code error'd out on the WGBS samples (see below) because there was a file missing from the directory /gscratch/scrubbed/sr320/froger-raw/00_fastq. The missing file was Meth1_R1_001.fastq.gz. @sr320 copied the missing file to the directory and I am currently re-running the trimming, hopefully with FastQC included now that I've added it to my path per @kubu4 's suggestions above, and with multiqc. Code is [here](https://gannet.fish.washington.edu/metacarcinus/mox_jobs/20200311_TrimGfroger.sh) and I added this to the [meth_compare_pipeline.rmd](https://github.com/hputnam/Meth_Compare/blob/master/analyses/Meth_Compare_Pipeline.md) under the 'Checking Sequence Quality and Trimming' section.
