### ISSUE TITLE
Explore why different methods produce different meth outcomes for each species

### ISSUE THREAD

**Issue by yaaminiv** [hputnam/Meth_Compare#47]

**Comment by shellywanamaker** [comment]
Mcap shows lower % reads map than Pact, possibly because of higher symbiont presence in Mcap (as proposed by Hollie today):

[![](https://raw.githubusercontent.com/hputnam/Meth_Compare/master/Output/Pact_Mcap_boxplot_methodXuniquely_mapped_reads.jpg)](https://raw.githubusercontent.com/hputnam/Meth_Compare/master/Output/Pact_Mcap_boxplot_methodXuniquely_mapped_reads.jpg)

fig. generated in this script: [FormatMultiQC.Rmd](https://github.com/hputnam/Meth_Compare/blob/master/analyses/FormatMultiQC/FormatMultiQC.Rmd)
