### ISSUE TITLE
Upload bismark bedgraphs, .cov, and .bam files to OSF

### ISSUE THREAD

**Issue by shellywanamaker** [hputnam/Meth_Compare#49]
Upload bismark bedgraphs, .cov, and .bam files to OSF ([https://osf.io/x5waz/](https://osf.io/x5waz/)) following the locations of files listed in the [Meth_Compare_Pipeline.md](https://github.com/hputnam/Meth_Compare/blob/master/analyses/Meth_Compare_Pipeline.md)

**Comment by sr320** [comment]
Many are too large in file size (5GB limit)

**Comment by sr320** [comment]
access to raw data and trimmed data on wiki https://osf.io/x5waz/wiki/home/

**Comment by sr320** [comment]
Bedgraphs on OSF

**Comment by sr320** [comment]
Merged coverage files on OSF

**Comment by sr320** [comment]
Bam alignment access on wiki

**Comment by kubu4** [comment]
A trick I used to get around the OSF 5GB file size for the geoduck genome repo (and can be used for GitHub stuff, too).

For a 5GB FastQ file called `example.fq`, run the following command:

`split example.fq example.fq- -d --bytes 1GB`

The output will be:

```
example.fq-01
example.fq-02
example.fq-03
example.fq-04
example.fq-05
```

All of them will be 1GB in size.

The code is doing the following:

- `split`: Program for splitting files

- `example.fq`: input file

- `example.fq-`: Sets prefix for output filenames

- `-d`: Use numeric suffix instead of alphabetical

- `--bytes 1GB`: Split file based on size of 1GB.

Then, you can concatenate them later:

```shell
for file in example.fq*
do
cat ${file} >> original.fq
done
```

The MD5 checksum of `original.fq` will match that of the original `example.fq`.

EDITED: Add code explanation.
