### ISSUE TITLE
Generate exon / intron tracks

### ISSUE THREAD

**Issue by sr320** [hputnam/Meth_Compare#6]

**Comment by yaaminiv** [comment]
Generated tracks found [here](https://github.com/hputnam/Meth_Compare/tree/master/genome-feature-files).

- *M. capitata*: genes, CDS (90% sure based on IGV that these are functionally exons, but will need to check the paper), introns
- *P. acuta*: genes, transcripts, CDS, exons (initial, internal, terminal, and all), introns

**Comment by yaaminiv** [comment]
Do we want to derive promoter, UTR, or intergenic region tracks?

**Comment by sr320** [comment]
yes - I would say lets get those tracks also

**Comment by yaaminiv** [comment]
I can't generate promoter and UTR tracks for *M. capitata*, so I won't make those for *P. acuta* since we're trying to make things comparable between species. I could make an intergenic track, but it seems rather redundant since I can use `bedtools intersect -v` with the pre-existing gene track from each genome to understand what overlaps with intergenic regions. I think for now we have all the tracks we need for our analyses, but I can generate more down the line if we decide to do something different.
