### ISSUE TITLE
Create bed files of different method-associated loci coverage

### ISSUE THREAD

**Issue by sr320** [hputnam/Meth_Compare#61]
This is in relation to "upset" plot discussion today.

Approach / downstream wise I would suggest taking the union bedgraph and simply parsing based  on approaches covering loci, recalling that in our conversation we stated only one sample per method would count. 

Resulting bed files would then easily go to Yaamini for feature analysis.

should be ~ 8 files?

MBD - WGBS - RRBS
MBD - WGBS
MBD - RRBS
WGBS - RRBS
WGBS only
MBD only 
RRBS only 
None

**Comment by shellywanamaker** [comment]
@yaaminiv here are the bed files:

**Mcap:**
- [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Mcap/Mcap_MBD_only_CpGs.bed](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Mcap/Mcap_MBD_only_CpGs.bed)
- [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Mcap/Mcap_RRBS_only_CpGs.bed](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Mcap/Mcap_RRBS_only_CpGs.bed)
- [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Mcap/Mcap_WGBS_only_CpGs.bed](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Mcap/Mcap_WGBS_only_CpGs.bed)
- [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Mcap/Mcap_WGBS_RRBS_only_CpGs.bed](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Mcap/Mcap_WGBS_RRBS_only_CpGs.bed)
- [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Mcap/Mcap_WGBS_MBD_only_CpGs.bed](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Mcap/Mcap_WGBS_MBD_only_CpGs.bed)
- [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Mcap/Mcap_RRBS_MBD_only_CpGs.bed](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Mcap/Mcap_RRBS_MBD_only_CpGs.bed)
- [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Mcap/Mcap_WGBS_RRBS_MBD_only_CpGs.bed](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Mcap/Mcap_WGBS_RRBS_MBD_only_CpGs.bed)

**Pact:**
- [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Pact/Pact_MBD_only_CpGs.bed](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Pact/Pact_MBD_only_CpGs.bed)
- [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Pact/Pact_RRBS_only_CpGs.bed](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Pact/Pact_RRBS_only_CpGs.bed)
- [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Pact/Pact_WGBS_only_CpGs.bed](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Pact/Pact_WGBS_only_CpGs.bed)
- [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Pact/Pact_WGBS_RRBS_only_CpGs.bed](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Pact/Pact_WGBS_RRBS_only_CpGs.bed)
- [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Pact/Pact_WGBS_MBD_only_CpGs.bed](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Pact/Pact_WGBS_MBD_only_CpGs.bed)
- [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Pact/Pact_RRBS_MBD_only_CpGs.bed](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Pact/Pact_RRBS_MBD_only_CpGs.bed)
- [https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Pact/Pact_WGBS_RRBS_MBD_only_CpGs.bed](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Pact/Pact_WGBS_RRBS_MBD_only_CpGs.bed)

you could also run the following code to download them if that's easier:
```
wget -r \
--no-directories --no-parent --reject "index.html*" \
-P . \
-A CpGs.bed https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Mcap/

wget -r \
--no-directories --no-parent --reject "index.html*" \
-P . \
-A CpGs.bed https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200504/data/Pact/
```
The columns are the same as the union bed file so there are more than 4 columns, but I don't think it should affect bedtools intersect because the first 3 columns are still:
1. Scaffold
2. Start
3. End
4. ALL (1 indicates CpG is in the genome)
5. WGBS (1 indicates CpG was detected by WGBS)
6. RRBS (1 indicates CpG was detected by RRBS)
7. MBD (1 indicates CpG was detected by MBD)

jupyter notebook used to create files is here: [https://github.com/hputnam/Meth_Compare/blob/master/scripts/Generate_UpsetPlot_input.ipynb](https://github.com/hputnam/Meth_Compare/blob/master/scripts/Generate_UpsetPlot_input.ipynb)

**Comment by shellywanamaker** [comment]
@yaaminiv NOTE: these files do not contain redundant CpGs. In other words, if a CpG is listed in one file, it is not listed in any other file.

**Comment by yaaminiv** [comment]
I identified genomic location in [this script](https://github.com/hputnam/Meth_Compare/blob/master/scripts/Identifying-Genomic-Locations.ipynb) and reformatted tables/created plots in [this R Markdown](https://github.com/hputnam/Meth_Compare/blob/master/scripts/Identifying-Genome-Features-Summary-Plots.Rmd).

- [Mcap summary counts](https://github.com/hputnam/Meth_Compare/blob/master/analyses/Identifying-genomic-locations/Mcap/Mcap-upset-data-Feature-Overlap-Counts.txt)
- [Mcap summary percents](https://github.com/hputnam/Meth_Compare/blob/master/analyses/Identifying-genomic-locations/Mcap/Mcap-upset-data-Feature-Overlap-Percents.txt)
- [Mcap stacked barplot](https://github.com/hputnam/Meth_Compare/blob/master/Output/Mcap-Upset-Feature-Overlaps.pdf)

![Screen Shot 2020-05-08 at 1 18 15 AM](https://user-images.githubusercontent.com/22335838/81386414-ce2b6c80-90c9-11ea-8d9d-7dc576937bf5.png)

(from bottom to top of each bar: CDS, introns, flanks, intergenic)

- [Pact summary counts](https://github.com/hputnam/Meth_Compare/blob/master/analyses/Identifying-genomic-locations/Pact/Pact-upset-data-Feature-Overlap-Counts.txt)
- [Pact summary percents](https://github.com/hputnam/Meth_Compare/blob/master/analyses/Identifying-genomic-locations/Pact/Pact-upset-data-Feature-Overlap-Percents.txt)
- [Pact stacked barplot]()

![Screen Shot 2020-05-08 at 1 26 18 AM](https://user-images.githubusercontent.com/22335838/81387067-ec459c80-90ca-11ea-9839-e4b02ba66434.png)

(from bottom to top of each bar: CDS, introns, flanks, intergenic)

Will tackle stats next
