### ISSUE TITLE
RRBS not trimmed correctly in fastp

### ISSUE THREAD

**Issue by sr320** [hputnam/Meth_Compare#7]

**Comment by kubu4** [comment]
Any more info on this?

**Comment by sr320** [comment]
![fastp-seq-content-gc-plot](https://user-images.githubusercontent.com/4442039/76150885-b4d35900-6063-11ea-9d37-2c749fd32a2b.png)

**Comment by kubu4** [comment]
Hmmm, well, fastp trimmed properly (per the arguments provided) and looks like I set the trimming correctly per the [Bismark trimming guidelines for RRBS](https://rawgit.com/FelixKrueger/Bismark/master/Docs/Bismark_User_Guide.html), i.e.

Read 1: rm 2bp from 3' end
Read 2: rm 2bp from 5' end

Is it possible that spike is expected due to the restriction enzyme site cleavage?

Alternatively, I an re-run this easily and trim the additional 2-3bp to get rid of that.

**Comment by mgavery** [comment]
yup, thanks
thinking that was % methylation, but just 100% are CG because of ezyme.
